name: Continuous integration
on: [push, pull_request]
jobs:
  build_tutorial:
    runs-on: ubuntu-latest
    steps:
      - name: Download Bazelisk
        uses: actions/download-artifact@v3
        with:
          name: bazelisk
          path: /usr/local/bin/bazel 
          url: https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64

      - name: Make Bazelisk executable
        run: chmod +x /usr/local/bin/bazel
        
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Build the tutorial target
        run: bazel build :tutorial
