name: Continuous integration
on: [push, pull_request]
jobs:
  build_tutorial:
    runs-on: ubuntu-latest
    steps:
      - name: Download Bazelisk
        run: sudo curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64

      - name: Make Bazelisk executable
        run: sudo chmod +x /usr/local/bin/bazel

      - name: Verify Bazelisk installation
        run: bazel --version

      - name: Install OS library dependencies
        run: sudo apt-get install -y libsasl2-dev libssl-dev libsnappy-dev libzstd-dev

      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Build the tutorial target
        run: bazel build :tutorial
